name: Cargo test

on:
  pull_request:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build_and_test:
    name: Octo sports - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build
      - run: cargo test

